--[[
    Shared UI element templates used by both LuxyHub and LuxyLibraryV2.
    Contains default configurations for all UI component types.
]]

local function CreateTemplates(Library)
    return {
        Frame = { BorderSizePixel = 0 },
        ImageLabel = { BackgroundTransparency = 1, BorderSizePixel = 0 },
        ImageButton = { AutoButtonColor = false, BorderSizePixel = 0 },
        ScrollingFrame = { BorderSizePixel = 0 },
        TextLabel = {
            BorderSizePixel = 0,
            FontFace = "Font",
            RichText = true,
            TextColor3 = "FontColor",
        },
        TextButton = {
            AutoButtonColor = false,
            BorderSizePixel = 0,
            FontFace = "Font",
            RichText = true,
            TextColor3 = "FontColor",
        },
        TextBox = {
            BorderSizePixel = 0,
            FontFace = "Font",
            PlaceholderColor3 = function()
                local H, S, V = Library.Scheme.FontColor:ToHSV()
                return Color3.fromHSV(H, S, V / 2)
            end,
            Text = "",
            TextColor3 = "FontColor",
        },
        UIListLayout = { SortOrder = Enum.SortOrder.LayoutOrder },
        UIStroke = { ApplyStrokeMode = Enum.ApplyStrokeMode.Border },
        Dialog = {
            Title = "Dialog",
            Description = "Description",
            AutoDismiss = true,
            AutoDestroy = false,
            OutsideClickDismiss = true,
            FooterButtons = {},
            StartHidden = false,
        },
        List = {
            Items = {},
            Multi = false,
            MaxHeight = 150,
            EmptyText = "No items",
            Callback = function() end,
            Changed = function() end,
            Disabled = false,
            Visible = true,
        },
        Toggle = {
            Text = "Toggle",
            Default = false,
            Callback = function() end,
            Changed = function() end,
            Risky = false,
            Disabled = false,
            Visible = true,
        },
        Input = {
            Text = "Input",
            Default = "",
            Finished = false,
            Numeric = false,
            ClearTextOnFocus = true,
            Placeholder = "",
            AllowEmpty = true,
            EmptyReset = "---",
            Callback = function() end,
            Changed = function() end,
            Disabled = false,
            Visible = true,
        },
        Slider = {
            Text = "Slider",
            Default = 0,
            Min = 0,
            Max = 100,
            Rounding = 0,
            Prefix = "",
            Suffix = "",
            Callback = function() end,
            Changed = function() end,
            Disabled = false,
            Visible = true,
        },
        Dropdown = {
            Values = {},
            DisabledValues = {},
            Multi = false,
            MaxVisibleDropdownItems = 8,
            Callback = function() end,
            Changed = function() end,
            Disabled = false,
            Visible = true,
        },
        Viewport = {
            Object = nil,
            Camera = nil,
            Clone = true,
            AutoFocus = true,
            Interactive = false,
            Height = 200,
            Visible = true,
        },
        Image = {
            Image = "",
            Transparency = 0,
            BackgroundTransparency = 0,
            Color = Color3.new(1, 1, 1),
            RectOffset = Vector2.zero,
            RectSize = Vector2.zero,
            ScaleType = Enum.ScaleType.Fit,
            Height = 200,
            Visible = true,
        },
        Video = {
            Video = "",
            Looped = false,
            Playing = false,
            Volume = 1,
            Height = 200,
            Visible = true,
        },
        UIPassthrough = {
            Instance = nil,
            Height = 24,
            Visible = true,
        },
        KeyPicker = {
            Text = "KeyPicker",
            Default = "None",
            DefaultModifiers = {},
            Mode = "Toggle",
            Modes = { "Always", "Toggle", "Hold" },
            SyncToggleState = false,
            Callback = function() end,
            ChangedCallback = function() end,
            Changed = function() end,
            Clicked = function() end,
        },
        ColorPicker = {
            Default = Color3.new(1, 1, 1),
            Callback = function() end,
            Changed = function() end,
        },
    }
end

return CreateTemplates
